// Bumps talater/homebrew-wrap Formula/wrap.rb to a new tag: recomputes
// sha256 for all three URLs (source archive + two macOS binaries) and opens
// a PR. Replaces dawidd6/action-homebrew-bump-formula whose brew-bump-pr
// backend only handles one arch at a time.
//
// Runs in CI with GH_TOKEN (PAT scoped to the tap) + TAG env set.

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { $ } from "bun";

const tag = process.env.TAG ?? process.argv[2];
if (!tag?.startsWith("v")) {
  console.error("Usage: TAG=v0.0.3 GH_TOKEN=… bun run scripts/bump-tap.ts");
  process.exit(1);
}
const version = tag.slice(1);
const repo = "talater/wrap";
const tap = "talater/homebrew-wrap";
const base = `https://github.com/${repo}`;

async function sha256(url: string): Promise<string> {
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  const h = new Bun.CryptoHasher("sha256");
  h.update(new Uint8Array(await res.arrayBuffer()));
  return h.digest("hex");
}

console.log(`Computing sha256 for ${tag}…`);
const [sourceSha, armSha, intelSha] = await Promise.all([
  sha256(`${base}/archive/refs/tags/${tag}.tar.gz`),
  sha256(`${base}/releases/download/${tag}/wrap-aarch64-apple-darwin.tar.gz`),
  sha256(`${base}/releases/download/${tag}/wrap-x86_64-apple-darwin.tar.gz`),
]);

const tapDir = mkdtempSync(join(tmpdir(), "tap-"));
await $`gh auth setup-git`.quiet();
await $`gh repo clone ${tap} ${tapDir} -- --depth=1`.quiet();
await $`git -C ${tapDir} config user.name "github-actions[bot]"`;
await $`git -C ${tapDir} config user.email "41898282+github-actions[bot]@users.noreply.github.com"`;

const branch = `bump-wrap-${version}`;
await $`git -C ${tapDir} checkout -b ${branch}`;

const formulaPath = `${tapDir}/Formula/wrap.rb`;
let src = await Bun.file(formulaPath).text();

// Each (url, sha256) pair is replaced atomically so a mid-run crash can't
// leave the formula half-bumped.
const pairs = [
  {
    urlRe:
      /url "https:\/\/github\.com\/talater\/wrap\/archive\/refs\/tags\/v[^"]+\.tar\.gz"(\s+)sha256 "[a-f0-9]{64}"/,
    url: `${base}/archive/refs/tags/${tag}.tar.gz`,
    sha: sourceSha,
  },
  {
    urlRe:
      /url "https:\/\/github\.com\/talater\/wrap\/releases\/download\/v[^/]+\/wrap-aarch64-apple-darwin\.tar\.gz"(\s+)sha256 "[a-f0-9]{64}"/,
    url: `${base}/releases/download/${tag}/wrap-aarch64-apple-darwin.tar.gz`,
    sha: armSha,
  },
  {
    urlRe:
      /url "https:\/\/github\.com\/talater\/wrap\/releases\/download\/v[^/]+\/wrap-x86_64-apple-darwin\.tar\.gz"(\s+)sha256 "[a-f0-9]{64}"/,
    url: `${base}/releases/download/${tag}/wrap-x86_64-apple-darwin.tar.gz`,
    sha: intelSha,
  },
];
for (const p of pairs) {
  const replacement = `url "${p.url}"$1sha256 "${p.sha}"`;
  const next = src.replace(p.urlRe, replacement);
  if (next === src) {
    console.error(`Pattern not found in ${formulaPath}: ${p.urlRe}`);
    process.exit(1);
  }
  src = next;
}
await Bun.write(formulaPath, src);

await $`git -C ${tapDir} add Formula/wrap.rb`;
const staged = (await $`git -C ${tapDir} diff --cached --name-only`.text()).trim();
if (!staged) {
  console.log("Formula already at target version — nothing to do.");
  process.exit(0);
}

await $`git -C ${tapDir} commit -m ${`wrap ${version}`}`;
await $`git -C ${tapDir} push origin ${branch} --force-with-lease`.quiet();

const body = `Auto-generated by the wrap release workflow.\n\nBumps wrap to ${tag}, recomputing sha256 for source archive and both macOS binaries.`;
const existing =
  await $`gh -R ${tap} pr list --head ${branch} --state open --json number -q '.[0].number'`
    .nothrow()
    .text();
if (existing.trim()) {
  console.log(`PR already open: ${tap}#${existing.trim()}`);
} else {
  await $`gh -R ${tap} pr create --title ${`wrap ${version}`} --body ${body} --head ${branch} --base main`;
}
