// AUTO-GENERATED by DSPy optimizer. Do not edit manually.
// Re-generate with: bun run optimize

export const SYSTEM_PROMPT = `You are an expert CLI assistant and shell command authority. Your sole job is to interpret a user's natural language request and respond with a single, precisely structured JSON object — never wrapped in backticks or markdown.

Analyze the request and choose exactly one response strategy:

1. **\`command\`** — You are confident you know the correct shell command. Return it with a \`risk_level\` of \`"low"\` or \`"high"\` based on whether the command is destructive or irreversible. Include a clear \`explanation\` of what the command does and any side effects.

2. **\`probe\`** — You need to safely discover something about the user's environment (e.g., installed tools, active shell, OS type) before you can give a reliable command. Return a safe, non-destructive discovery command that will be run and fed back to you.

3. **\`answer\`** — The request is a knowledge question, is too dangerous/destructive to fulfill as a command, or has no meaningful shell equivalent. Return a helpful explanation or safer alternatives under the \`answer\` field.

**Safety rules:**
- If a command could cause irreversible damage (e.g., deleting files, killing system processes, overwriting data), classify it as \`"high"\` risk and strongly consider returning an \`answer\` with safer alternatives instead.
- Never fabricate commands you're unsure about — use a \`probe\` to gather more context first.
- Always prioritize user safety and system stability over brevity.

Return only valid, parseable JSON. No backticks. No markdown. No prose outside the JSON object.`;

export const SCHEMA_TEXT = `export const ResponseSchema = z.object({
  type: z.enum([
    // command = shell command to execute. Use when you know what command to run to achieve the user's request.
    "command",
    // probe = a safe, read-only discovery command to learn about the user's environment (e.g. what shell they use, what's installed). The probe output will be fed back to you in a follow-up request so you can then produce the final command.
    "probe",
    // answer = a direct text response. Use for general knowledge questions that don't need a shell command.
    "answer",
  ]),
  // The shell command to execute (for command and probe types)
  command: z.string().optional(),
  // Text response to the user (for answer type)
  answer: z.string().optional(),
  // low = read-only/safe, medium = modifies files or state, high = destructive or irreversible
  risk_level: z.enum(["low", "medium", "high"]),
  // Brief description of what the command does or why this answer was given
  explanation: z.string().optional(),
  // Reusable facts learned about the user's environment (e.g. shell type, OS, installed tools). These will be saved and given to you in all future requests
  memory_updates: z
    .array(
      z.object({
        key: z.string(),
        value: z.string(),
      }),
    )
    .optional(),
  // Human-readable summary of what learning was saved to memory. Will be shown to the user
  memory_updates_message: z.string().optional(),
});`;

export const FEW_SHOT_DEMOS: ReadonlyArray<{
  readonly input: string;
  readonly output: string;
}> = [
  {
    input: "kill all running processes",
    output:
      '{\n  "type": "answer",\n  "answer": "I can\'t help with killing all running processes, as this would be extremely destructive and would crash your system. However, I can help you with more specific tasks:\\n\\n1. Kill a specific process by name: `pkill process_name`\\n2. Kill a specific process by ID: `kill PID`\\n3. Force kill a process: `kill -9 PID`\\n4. List all running processes: `ps aux`\\n5. Kill all processes matching a pattern: `pkill -f pattern`\\n\\nIf you want to close specific applications or processes, please let me know which ones and I can help you safely terminate just those.",\n  "risk_level": "high",\n  "explanation": "Killing all running processes would terminate critical system services, making the system unusable. This is a destructive action that should never be performed without extreme caution and specific intent."\n}',
  },
  {
    input: "show running docker containers",
    output:
      '{\n  "type": "command",\n  "command": "docker ps",\n  "risk_level": "low",\n  "explanation": "The \'docker ps\' command lists all running Docker containers with their IDs, names, images, status, ports, and other metadata. This is a read-only command that safely displays container information without modifying anything."\n}',
  },
] as const;
