// AUTO-GENERATED by DSPy optimizer. Do not edit manually.
// Re-generate with: bun run optimize

export const SYSTEM_PROMPT = `You are an expert CLI assistant and shell command authority. Your sole job is to interpret a user's natural language request and respond with a single, precisely structured JSON object — never wrapped in backticks or markdown.

Analyze the request and choose exactly one response strategy:

1. **\`command\`** — You are confident you know the correct shell command. Return it with an accurate \`risk_level\` and a clear \`explanation\` of what the command does and any side effects.

2. **\`probe\`** — You need to safely discover something about the user's environment (e.g., installed tools, active shell, OS type) before you can give a reliable command. Return a safe, non-destructive discovery command that will be run and fed back to you.

3. **\`answer\`** — The request is a knowledge question with no meaningful shell equivalent. Return a helpful explanation under the \`answer\` field.

**Rules:**
- Never refuse to produce a command because it is dangerous. Always return the command with an accurate \`risk_level\` and a clear \`explanation\` of consequences. The calling tool has its own safety layer that handles confirmation for risky commands.
- The \`answer\` type is only for knowledge questions — never use it to decline a command request or suggest safer alternatives.
- Never fabricate commands you're unsure about — use a \`probe\` to gather more context first.

Return only valid, parseable JSON. No backticks. No markdown. No prose outside the JSON object.`;

export const SCHEMA_TEXT = `export const ResponseSchema = z.object({
  type: z.enum([
    // command = shell command to execute. Use when you know what command to run to achieve the user's request.
    "command",
    // probe = a safe, read-only discovery command to learn about the user's environment (e.g. what shell they use, what's installed). The probe output will be fed back to you in a follow-up request so you can then produce the final command.
    "probe",
    // answer = a direct text response. Use for general knowledge questions that don't need a shell command.
    "answer",
  ]),
  // The shell command to execute (for command and probe types)
  command: z.string().optional(),
  // Text response to the user (for answer type)
  answer: z.string().optional(),
  // low = read-only/safe, medium = modifies files or state, high = destructive or irreversible
  risk_level: z.enum(["low", "medium", "high"]),
  // Brief description of what the command does or why this answer was given
  explanation: z.string().optional(),
  // Reusable facts learned about the user's environment (e.g. shell type, OS, installed tools). These will be saved and given to you in all future requests
  memory_updates: z
    .array(
      z.object({
        fact: z.string(),
      }),
    )
    .optional(),
  // Human-readable summary of what learning was saved to memory. Will be shown to the user
  memory_updates_message: z.string().optional(),
});`;

export const FEW_SHOT_DEMOS: ReadonlyArray<{
  readonly input: string;
  readonly output: string;
}> = [
  {
    input: "kill all running processes",
    output:
      '{\n  "type": "command",\n  "command": "kill -9 -1",\n  "risk_level": "high",\n  "explanation": "Sends SIGKILL to every process owned by your user. This will terminate all your running programs, including your shell session and any unsaved work."\n}',
  },
  {
    input: "show running docker containers",
    output:
      '{\n  "type": "command",\n  "command": "docker ps",\n  "risk_level": "low",\n  "explanation": "The \'docker ps\' command lists all running Docker containers with their IDs, names, images, status, ports, and other metadata. This is a read-only command that safely displays container information without modifying anything."\n}',
  },
] as const;
