import { chrome } from "../core/output.ts";
import type { CLIFlag, Command, CompletionKind, Option } from "./types.ts";

const SUPPORTED_SHELLS = ["zsh", "bash", "fish"] as const;
type Shell = (typeof SUPPORTED_SHELLS)[number];

const DEFAULT_NAME = "wrap";
// Restrict to bash-compatible identifiers so `_<name>` is a valid function
// name in every supported shell (bash is strictest).
const NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

const HINT = "Run `wrap --help completion` for install instructions.";

type Registry = {
  commands: readonly Command[];
  options: readonly Option[];
  providers: readonly string[];
};

function flagNames(flag: CLIFlag): string[] {
  return [flag.flag, ...(flag.aliases ?? [])];
}

function takesValue(flag: CLIFlag): boolean {
  if (flag.completion) return true;
  return flag.kind === "option" && flag.takesValue;
}

// Unescaped `]` terminates [description]; `\` and `'` break single-quoted spec.
function escapeZshDesc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/]/g, "\\]").replace(/'/g, "'\\''");
}

function zshValueAction(flag: CLIFlag, name: string): string {
  if (flag.completion === "providers") return `:provider:_${name}_providers`;
  if (flag.completion === "shells") return `:shell:(${SUPPORTED_SHELLS.join(" ")})`;
  return "";
}

function zshFlagSpecs(flag: CLIFlag, name: string): string[] {
  const desc = escapeZshDesc(flag.description);
  const names = flagNames(flag);
  // Exclusion list hides aliases once one has been typed.
  const exclusion = names.length > 1 ? `(${names.join(" ")})` : "";
  const valuePrefix = takesValue(flag) ? "=" : "";
  const suffix = `${valuePrefix}[${desc}]${zshValueAction(flag, name)}`;
  return names.map((flagName) => `'${exclusion}${flagName}${suffix}'`);
}

export function generateZshCompletion(registry: Registry, name: string = DEFAULT_NAME): string {
  const specs: string[] = [];
  for (const flag of [...registry.commands, ...registry.options]) {
    specs.push(...zshFlagSpecs(flag, name));
  }
  const providers = registry.providers.map((n) => `'${escapeZshDesc(n)}'`).join(" ");

  return `#compdef ${name}
# Generated by \`${name} --completion zsh\`. Do not edit by hand.

_${name}_providers() {
  local -a providers=(${providers})
  compadd -S ':' -q -- "\${providers[@]}"
}

_${name}() {
  _arguments -s \\
    ${specs.join(" \\\n    ")}
}

_${name} "$@"
`;
}

function bashCasePattern(registry: Registry, kind: CompletionKind): string {
  return [...registry.commands, ...registry.options]
    .filter((f) => f.completion === kind)
    .flatMap(flagNames)
    .join("|");
}

export function generateBashCompletion(registry: Registry, name: string = DEFAULT_NAME): string {
  const allNames = [...registry.commands, ...registry.options].flatMap(flagNames);
  // Trailing colon + `compopt -o nospace` mirrors zsh's `-S ':' -q` UX:
  // tab gives `anthropic:`, user continues typing the model without a stray space.
  const providerWords = registry.providers.map((p) => `${p}:`).join(" ");
  const shellWords = SUPPORTED_SHELLS.join(" ");
  const providerPat = bashCasePattern(registry, "providers");
  const shellPat = bashCasePattern(registry, "shells");

  const caseArms: string[] = [];
  if (providerPat) {
    caseArms.push(
      `    ${providerPat})
      COMPREPLY=($(compgen -W "${providerWords}" -- "$cur"))
      compopt -o nospace 2>/dev/null
      return
      ;;`,
    );
  }
  if (shellPat) {
    caseArms.push(
      `    ${shellPat})
      COMPREPLY=($(compgen -W "${shellWords}" -- "$cur"))
      return
      ;;`,
    );
  }
  const caseBlock =
    caseArms.length > 0 ? `  case "$prev" in\n${caseArms.join("\n")}\n  esac\n\n` : "";

  return `# Generated by \`${name} --completion bash\`. Do not edit by hand.

_${name}() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

${caseBlock}  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "${allNames.join(" ")}" -- "$cur"))
  fi
}

complete -F _${name} ${name}
`;
}

// Fish single-quoted strings only honor `\\` and `\'` escapes.
function escapeFishSingle(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function fishCompleteLine(
  flag: CLIFlag,
  flagName: string,
  providers: readonly string[],
  cmdName: string,
): string {
  const parts = ["complete", "-c", cmdName];
  if (flagName.startsWith("--")) parts.push("-l", flagName.slice(2));
  else if (flagName.startsWith("-")) parts.push("-s", flagName.slice(1));

  if (flag.completion === "providers") {
    parts.push("-x", "-a", `'${providers.map(escapeFishSingle).join(" ")}'`);
  } else if (flag.completion === "shells") {
    parts.push("-x", "-a", `'${SUPPORTED_SHELLS.join(" ")}'`);
  } else if (takesValue(flag)) {
    parts.push("-x");
  }

  parts.push("-d", `'${escapeFishSingle(flag.description)}'`);
  return parts.join(" ");
}

export function generateFishCompletion(registry: Registry, name: string = DEFAULT_NAME): string {
  const lines = [`# Generated by \`${name} --completion fish\`. Do not edit by hand.`, ""];
  for (const flag of [...registry.commands, ...registry.options]) {
    for (const flagName of flagNames(flag)) {
      lines.push(fishCompleteLine(flag, flagName, registry.providers, name));
    }
  }
  return `${lines.join("\n")}\n`;
}

export function generateCompletion(
  shell: Shell,
  registry: Registry,
  name: string = DEFAULT_NAME,
): string {
  switch (shell) {
    case "zsh":
      return generateZshCompletion(registry, name);
    case "bash":
      return generateBashCompletion(registry, name);
    case "fish":
      return generateFishCompletion(registry, name);
  }
}

async function loadRegistry(): Promise<Registry> {
  const { commands, options } = await import("./registry.ts");
  const { API_PROVIDERS, CLI_PROVIDERS } = await import("../llm/providers/registry.ts");
  return {
    commands,
    options,
    providers: [...Object.keys(API_PROVIDERS), ...Object.keys(CLI_PROVIDERS)],
  };
}

type RunResult = { shell: Shell; name: string } | { error: string };

export function runCompletion(args: string[]): RunResult {
  if (args.length === 0 || args[0] === "") {
    return {
      error: `--completion requires a shell name (${SUPPORTED_SHELLS.join("/")}). ${HINT}`,
    };
  }
  if (args.length > 2) {
    return {
      error: `--completion takes at most two arguments (shell and optional name). ${HINT}`,
    };
  }
  const shell = args[0] as string;
  if (!SUPPORTED_SHELLS.includes(shell as Shell)) {
    return {
      error: `Unsupported shell: ${shell}. Supported: ${SUPPORTED_SHELLS.join(", ")}. ${HINT}`,
    };
  }
  const name = args[1] ?? DEFAULT_NAME;
  if (!NAME_PATTERN.test(name)) {
    return {
      error: `Invalid name: ${JSON.stringify(name)}. Must start with a letter or underscore and contain only letters, digits, and underscores.`,
    };
  }
  return { shell: shell as Shell, name };
}

export const completionCmd: Command = {
  kind: "command",
  flag: "--completion",
  aliases: ["--completions"],
  completion: "shells",
  id: "completion",
  description: "Print shell completion script",
  usage: "w --completion <shell> [name]",
  help: [
    `Supported shells: ${SUPPORTED_SHELLS.join(", ")}`,
    "",
    "By default the completion registers the command name `wrap`. Pass an optional",
    "second argument to register a different name (e.g. a shell alias).",
    "",
    "Install (zsh):",
    "  wrap --completion zsh > ~/.zsh/completions/_wrap",
    "  (ensure the directory is on your $fpath, then run `compinit`)",
    "",
    "Install (bash):",
    "  wrap --completion bash > ~/.local/share/bash-completion/completions/wrap",
    "",
    "Install (fish):",
    "  wrap --completion fish > ~/.config/fish/completions/wrap.fish",
  ].join("\n"),
  run: async (args) => {
    const result = runCompletion(args);
    if ("error" in result) {
      chrome(result.error);
      process.exitCode = 1;
      return;
    }
    process.stdout.write(generateCompletion(result.shell, await loadRegistry(), result.name));
  },
};
