import { chrome } from "../core/output.ts";
import type { CLIFlag, Command, Option } from "./types.ts";

const SUPPORTED_SHELLS = ["zsh"] as const;
type SupportedShell = (typeof SUPPORTED_SHELLS)[number];

const HINT = "Run `w --help completion` for install instructions.";

// Unescaped `]` terminates [description]; `\` and `'` break single-quoted spec.
function escapeDesc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/]/g, "\\]").replace(/'/g, "'\\''");
}

function valueAction(flag: CLIFlag): string {
  if (flag.completion === "providers") return ":provider:_w_providers";
  if (flag.completion === "shells") return `:shell:(${SUPPORTED_SHELLS.join(" ")})`;
  return "";
}

function takesValue(flag: CLIFlag): boolean {
  if (flag.completion) return true;
  return flag.kind === "option" && flag.takesValue;
}

function flagSpecs(flag: CLIFlag): string[] {
  const desc = escapeDesc(flag.description);
  const names = [flag.flag, ...(flag.aliases ?? [])];
  // Exclusion list hides aliases once one has been typed.
  const exclusion = names.length > 1 ? `(${names.join(" ")})` : "";
  const valuePrefix = takesValue(flag) ? "=" : "";
  const suffix = `${valuePrefix}[${desc}]${valueAction(flag)}`;
  return names.map((name) => `'${exclusion}${name}${suffix}'`);
}

type Registry = {
  commands: readonly Command[];
  options: readonly Option[];
  providers: readonly string[];
};

async function loadRegistry(): Promise<Registry> {
  const { commands, options } = await import("./registry.ts");
  const { API_PROVIDERS, CLI_PROVIDERS } = await import("../llm/providers/registry.ts");
  return {
    commands,
    options,
    providers: [...Object.keys(API_PROVIDERS), ...Object.keys(CLI_PROVIDERS)],
  };
}

export function generateZshCompletion(registry: Registry): string {
  const specs: string[] = [];
  for (const flag of [...registry.commands, ...registry.options]) {
    specs.push(...flagSpecs(flag));
  }
  const providers = registry.providers.map((n) => `'${escapeDesc(n)}'`).join(" ");

  return `#compdef w
# Generated by \`w --completion zsh\`. Do not edit by hand.

_w_providers() {
  local -a providers=(${providers})
  compadd -S ':' -q -- "\${providers[@]}"
}

_w() {
  _arguments -s \\
    ${specs.join(" \\\n    ")}
}

_w "$@"
`;
}

type RunResult = "ok" | { error: string };

export function runCompletion(args: string[]): RunResult {
  if (args.length === 0 || args[0] === "") {
    return { error: `--completion requires a shell name (zsh). ${HINT}` };
  }
  if (args.length > 1) {
    return { error: "--completion takes one argument." };
  }
  const shell = args[0] as string;
  if (!SUPPORTED_SHELLS.includes(shell as SupportedShell)) {
    return {
      error: `Unsupported shell: ${shell}. Supported: ${SUPPORTED_SHELLS.join(", ")}. ${HINT}`,
    };
  }
  return "ok";
}

export const completionCmd: Command = {
  kind: "command",
  flag: "--completion",
  aliases: ["--completions"],
  completion: "shells",
  id: "completion",
  description: "Print shell completion script",
  usage: "w --completion <shell>",
  help: [
    "Supported shells: zsh",
    "",
    "Install:",
    "  w --completion zsh > ~/.zsh/completions/_w",
    "",
    "Make sure the directory is on your $fpath and re-run `compinit`.",
  ].join("\n"),
  run: async (args) => {
    const result = runCompletion(args);
    if (result !== "ok") {
      chrome(result.error);
      process.exit(1);
      return;
    }
    process.stdout.write(generateZshCompletion(await loadRegistry()));
  },
};
