import { chrome } from "../core/output.ts";
import type { CLIFlag, Command, CompletionKind, Option } from "./types.ts";

const SUPPORTED_SHELLS = ["zsh", "bash", "fish"] as const;
type Shell = (typeof SUPPORTED_SHELLS)[number];

const HINT = "Run `w --help completion` for install instructions.";

type Registry = {
  commands: readonly Command[];
  options: readonly Option[];
  providers: readonly string[];
};

function flagNames(flag: CLIFlag): string[] {
  return [flag.flag, ...(flag.aliases ?? [])];
}

function takesValue(flag: CLIFlag): boolean {
  if (flag.completion) return true;
  return flag.kind === "option" && flag.takesValue;
}

// Unescaped `]` terminates [description]; `\` and `'` break single-quoted spec.
function escapeZshDesc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/]/g, "\\]").replace(/'/g, "'\\''");
}

function zshValueAction(flag: CLIFlag): string {
  if (flag.completion === "providers") return ":provider:_w_providers";
  if (flag.completion === "shells") return `:shell:(${SUPPORTED_SHELLS.join(" ")})`;
  return "";
}

function zshFlagSpecs(flag: CLIFlag): string[] {
  const desc = escapeZshDesc(flag.description);
  const names = flagNames(flag);
  // Exclusion list hides aliases once one has been typed.
  const exclusion = names.length > 1 ? `(${names.join(" ")})` : "";
  const valuePrefix = takesValue(flag) ? "=" : "";
  const suffix = `${valuePrefix}[${desc}]${zshValueAction(flag)}`;
  return names.map((name) => `'${exclusion}${name}${suffix}'`);
}

export function generateZshCompletion(registry: Registry): string {
  const specs: string[] = [];
  for (const flag of [...registry.commands, ...registry.options]) {
    specs.push(...zshFlagSpecs(flag));
  }
  const providers = registry.providers.map((n) => `'${escapeZshDesc(n)}'`).join(" ");

  return `#compdef w
# Generated by \`w --completion zsh\`. Do not edit by hand.

_w_providers() {
  local -a providers=(${providers})
  compadd -S ':' -q -- "\${providers[@]}"
}

_w() {
  _arguments -s \\
    ${specs.join(" \\\n    ")}
}

_w "$@"
`;
}

function bashCasePattern(registry: Registry, kind: CompletionKind): string {
  return [...registry.commands, ...registry.options]
    .filter((f) => f.completion === kind)
    .flatMap(flagNames)
    .join("|");
}

export function generateBashCompletion(registry: Registry): string {
  const allNames = [...registry.commands, ...registry.options].flatMap(flagNames);
  // Trailing colon + `compopt -o nospace` mirrors zsh's `-S ':' -q` UX:
  // tab gives `anthropic:`, user continues typing the model without a stray space.
  const providerWords = registry.providers.map((p) => `${p}:`).join(" ");
  const shellWords = SUPPORTED_SHELLS.join(" ");
  const providerPat = bashCasePattern(registry, "providers");
  const shellPat = bashCasePattern(registry, "shells");

  const caseArms: string[] = [];
  if (providerPat) {
    caseArms.push(
      `    ${providerPat})
      COMPREPLY=($(compgen -W "${providerWords}" -- "$cur"))
      compopt -o nospace 2>/dev/null
      return
      ;;`,
    );
  }
  if (shellPat) {
    caseArms.push(
      `    ${shellPat})
      COMPREPLY=($(compgen -W "${shellWords}" -- "$cur"))
      return
      ;;`,
    );
  }
  const caseBlock =
    caseArms.length > 0 ? `  case "$prev" in\n${caseArms.join("\n")}\n  esac\n\n` : "";

  return `# Generated by \`w --completion bash\`. Do not edit by hand.

_w() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

${caseBlock}  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "${allNames.join(" ")}" -- "$cur"))
  fi
}

complete -F _w w
`;
}

// Fish single-quoted strings only honor `\\` and `\'` escapes.
function escapeFishSingle(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function fishCompleteLine(flag: CLIFlag, name: string, providers: readonly string[]): string {
  const parts = ["complete", "-c", "w"];
  if (name.startsWith("--")) parts.push("-l", name.slice(2));
  else if (name.startsWith("-")) parts.push("-s", name.slice(1));

  if (flag.completion === "providers") {
    parts.push("-x", "-a", `'${providers.map(escapeFishSingle).join(" ")}'`);
  } else if (flag.completion === "shells") {
    parts.push("-x", "-a", `'${SUPPORTED_SHELLS.join(" ")}'`);
  } else if (takesValue(flag)) {
    parts.push("-x");
  }

  parts.push("-d", `'${escapeFishSingle(flag.description)}'`);
  return parts.join(" ");
}

export function generateFishCompletion(registry: Registry): string {
  const lines = ["# Generated by `w --completion fish`. Do not edit by hand.", ""];
  for (const flag of [...registry.commands, ...registry.options]) {
    for (const name of flagNames(flag)) {
      lines.push(fishCompleteLine(flag, name, registry.providers));
    }
  }
  return `${lines.join("\n")}\n`;
}

export function generateCompletion(shell: Shell, registry: Registry): string {
  switch (shell) {
    case "zsh":
      return generateZshCompletion(registry);
    case "bash":
      return generateBashCompletion(registry);
    case "fish":
      return generateFishCompletion(registry);
  }
}

async function loadRegistry(): Promise<Registry> {
  const { commands, options } = await import("./registry.ts");
  const { API_PROVIDERS, CLI_PROVIDERS } = await import("../llm/providers/registry.ts");
  return {
    commands,
    options,
    providers: [...Object.keys(API_PROVIDERS), ...Object.keys(CLI_PROVIDERS)],
  };
}

type RunResult = "ok" | { error: string };

export function runCompletion(args: string[]): RunResult {
  if (args.length === 0 || args[0] === "") {
    return {
      error: `--completion requires a shell name (${SUPPORTED_SHELLS.join("/")}). ${HINT}`,
    };
  }
  if (args.length > 1) {
    return { error: "--completion takes one argument." };
  }
  const shell = args[0] as string;
  if (!SUPPORTED_SHELLS.includes(shell as Shell)) {
    return {
      error: `Unsupported shell: ${shell}. Supported: ${SUPPORTED_SHELLS.join(", ")}. ${HINT}`,
    };
  }
  return "ok";
}

export const completionCmd: Command = {
  kind: "command",
  flag: "--completion",
  aliases: ["--completions"],
  completion: "shells",
  id: "completion",
  description: "Print shell completion script",
  usage: "w --completion <shell>",
  help: [
    `Supported shells: ${SUPPORTED_SHELLS.join(", ")}`,
    "",
    "Install (zsh):",
    "  w --completion zsh > ~/.zsh/completions/_w",
    "  (ensure the directory is on your $fpath, then run `compinit`)",
    "",
    "Install (bash):",
    "  w --completion bash > ~/.local/share/bash-completion/completions/w",
    "",
    "Install (fish):",
    "  w --completion fish > ~/.config/fish/completions/w.fish",
  ].join("\n"),
  run: async (args) => {
    const result = runCompletion(args);
    if (result !== "ok") {
      chrome(result.error);
      process.exit(1);
      return;
    }
    const shell = args[0] as Shell;
    process.stdout.write(generateCompletion(shell, await loadRegistry()));
  },
};
